In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from word2number import w2n
from sklearn.linear_model import LinearRegression

In [2]:
df=pd.read_csv('C:\Data\Custom\hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [3]:
df.experience = df.experience.fillna("zero")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [4]:
df.experience=df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [5]:
import math
test_score_median=math.floor(df['test_score(out of 10)'].mean())
test_score_median

7

In [6]:
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(test_score_median)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [7]:
model=LinearRegression()

In [8]:
model.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

In [9]:
model.predict([[2,9,6]])

array([53713.86677124])

In [10]:
import pickle

In [11]:
with open('Trained Model with Pickle','wb') as f:
    pickle.dump(model,f)

In [14]:
with open('Trained Model with Pickle','rb') as f:
    mo1=pickle.load(f)

In [15]:
print(mo1)

LinearRegression()


In [16]:
import joblib

In [17]:
joblib.dump(model,'Trained Model with Joblib')

['Trained Model with Joblib']

In [18]:
mo2=joblib.load('Trained Model with Joblib')

In [19]:
print(mo2)

LinearRegression()


In [21]:
mo2.predict([[5,6,7]])

array([57964.2290839])

In [23]:
mo1.predict([[5,6,7]])

array([57964.2290839])